export enum TeamPerformanceQualifier {
    TOPPER="TOPPER", UITSTEKEND="UITSTEKEND", ZEER_GOED="ZEER_GOED", GOED="GOED", BEHOORLIJK="BEHOORLIJK", FLOPPER="FLOPPER", ZEER_SLECHT="ZEER_SLECHT", SLECHT="SLECHT", ONDERMAATS="ONDERMAATS", MATIG="MATIG"
}
